### ISSUE TITLE
[M] Terug-/Vooruitknop

### ISSUE THREAD

**Issue by HighCrit** [HighCrit/WebBrowser-Cyanide-#3]
~0,5-1h

**Comment by HighCrit** [comment]
De terug en vooruitknop lopen een website achter, dus je eerste website kan je niet meer terug (je moet nog een website bezoeken om terug te gaan) en de button blijft dus geenabled terwijl je niet langer terug kan.

**Comment by WouterBurgt** [comment]
50 minuten
